### ISSUE TITLE
What is the format of the training data?

### ISSUE THREAD

**Issue by d-b-h** [nianticlabs/monodepth2#106]
I would like to retrain the monocular depth model with my own data. How should the dataset be organized? Is there a specific way to format the images?

**Comment by macaodha** [comment]
Hi @d-b-h,

I would suggest taking a look at the code and checking out similar questions (see below) other people have already posted. If there are still questions feel free to post here, but otherwise I'm closing this for now. 

https://github.com/nianticlabs/monodepth2/issues/86
https://github.com/nianticlabs/monodepth2/issues/77
https://github.com/nianticlabs/monodepth2/issues/71
