### ISSUE TITLE
How to optimize training

### ISSUE THREAD

**Issue by yuliang1995** [nianticlabs/monodepth2#116]
![000052](https://user-images.githubusercontent.com/39020380/70014593-2c51a200-15b6-11ea-8c33-93d6c571b7f0.jpg)
![000052_disp](https://user-images.githubusercontent.com/39020380/70014595-2c51a200-15b6-11ea-94f6-ca9464994681.jpeg)

I found that the effect was not obvious after training,is there any way to improve.
I use
K=[1.09, 0, 0.5,  0]
     [0, 1.94, 0.5, 0]
     [0 , 0 , 1 , 0]
     [0 , 0 , 0 , 1]
epoch=20,resnet=18 ,input=320*192

_Originally posted by @yuliang1995 in https://github.com/nianticlabs/monodepth2/issues/99#issuecomment-560970384_

**Comment by mrharicot** [comment]
Hi,
What is your question?

**Comment by yuliang1995** [comment]
I want to train indoor data.
I use the data I collect for training.
I can't make the pillars the same depth.
![000002](https://user-images.githubusercontent.com/39020380/70370634-68fa0200-1904-11ea-80dc-5968a8718cf7.jpg)
![000000](https://user-images.githubusercontent.com/39020380/70370635-69929880-1904-11ea-87da-2da7f9c268f9.jpg)
![000001](https://user-images.githubusercontent.com/39020380/70370636-69929880-1904-11ea-8e83-8c024a9d47ed.jpg)
train_files.txt 
I use consecutive numbers,
ex:
indoor1 000001 l
indoor1 000002 l
indoor1 000003 l 
indoor1 000004 l..

**Comment by mrharicot** [comment]
Hi,
I see several issues with your data:
1) It is both noisy and very compressed, you can see a lot of noise and compression on the pillar.
This is an issue since monodepth2 is a self supervised method, which means it relies on pixel similarities to learn, so the better quality the images the better.
2) There is not enough camera motion between your images. You need a sufficient amount of translation between images in order to create parallax.
