### ISSUE TITLE
slow speed with mono training

### ISSUE THREAD

**Issue by yzp12** [nianticlabs/monodepth2#125]
Hi,
I am getting the reported training time for stereo training, i.e. ~8 hours. However, if I use mono training, the expected finish time is ~80 hours. num example per second is ~4.  I dig in a bit it seems the added pose prediction part takes a long time. Any idea why? I am using pytorch0.4.1, python 3.7, cuda 9.2
Thank you!

**Comment by mrharicot** [comment]
Hi,
It is hard to tell without knowing what your system is. 

What is your gpu and are you storing your data on an SSD?
Mono training loads 4 images per sample instead of 2 for stereo, if you disk is slow it will make training much slower. 
You can verify this by checking the gpu usage using nvidia-smi, if it is not sustained in the high +90% it means something else is slowing it down.

**Comment by WANG-KX** [comment]
Actually I have tried using the intrinsic parameters from the KITTI dataset but did not observe any improvement in the accuracy. Confused about the result. Any different result is welcomed to be posted here.

**Comment by Ravenclaw-Hcmut** [comment]
> Hi, It is hard to tell without knowing what your system is.
> 
> What is your gpu and are you storing your data on an SSD? Mono training loads 4 images per sample instead of 2 for stereo, if you disk is slow it will make training much slower. You can verify this by checking the gpu usage using nvidia-smi, if it is not sustained in the high +90% it means something else is slowing it down.

Hi,

Can you explain why we use 4 images for monocular training. I think they are the previous frame, the current frame, the next frame, and what is the fourth frame?

Thank you.
