### ISSUE TITLE
some confusions between monodepth2 and monodepth1

### ISSUE THREAD

**Issue by Rinstein** [nianticlabs/monodepth2#132]
Firstly, thanks your nice work guid me in building depth map.
Here, I am comfused about two version monodepth2 in some aspect. Monodepth1 definitely adapts disparity as nn output，then real distance calculate by b*f/disparity, this is based on stereo system. Is monodepth also calculate  disparity，or directly real distance? If disparity, how can get real distance only through monocular vedio?

**Comment by alwynmathew** [comment]
You are right, monodepth1 predicts disparity and depth = b*f/disparity.
Monodpeth2 predicts inverse depth( ie., 1/depth) because it's better to optimize the depth model to predict values between 0 and 1 [link to code line](https://github.com/nianticlabs/monodepth2/blob/master/networks/depth_decoder.py#L63), and then scale it to 0.1 to 100 [link to code line](https://github.com/nianticlabs/monodepth2/blob/master/trainer.py#L354). 

At inference, 
* for the monocular video trained model, you just need to take the prediction from the depth model and scale it to 0.1-100 to get real depth [link to code line](https://github.com/nianticlabs/monodepth2/blob/master/evaluate_depth.py#L116)
* for the stereo trained model, you should be little more careful because of the trick(trained with a nominal baseline of 0.1 units) used to stabilize the training [link to code line](https://github.com/nianticlabs/monodepth2/blob/master/evaluate_depth.py#L24). Therefore, to convert the stereo predictions to real-world scale, you need to multiply network prediction by 5.4 [link to code line](https://github.com/nianticlabs/monodepth2/blob/master/evaluate_depth.py#L156)

**Comment by Rinstein** [comment]
ok，thanks
