### ISSUE TITLE
a little question about pose

### ISSUE THREAD

**Issue by sunnyHelen** [nianticlabs/monodepth2#17]
I'm trying to figure out the transform relationship among frames.
![image](https://user-images.githubusercontent.com/28101548/59160858-4c7c3900-8b1e-11e9-89c5-658483b4d59c.png)
After this step, are we getting T0→-1 and T0→1 OR T-1→0 and T0→1？
Thank you~

**Comment by mdfirman** [comment]
The `axisangle` and `translation` predictions are both forward in time, i.e T-1→0 and T0→1. This means the pose network only ever has to learn to predict transformations in one direction, which I suppose makes life a bit easier for it.

However, after `transformation_from_parameters` is applied we have T0→-1 and T0→1. The `invert` argument ensures that all transforms are now relative to T0, ensuring that all warped images appear back in the reference frame of the input image.

Hope this helps, thanks.

**Comment by ezorfa** [comment]
Hi @mdfirman @mrharicot !
When you said 
> The axisangle and translation predictions are both forward in time, i.e T-1→0 and T0→1

I think this statement is valid only for pose prediction in the case for **2 input frames** and **doesnt** hold when we input **more than two frames?** Could you clarify this please, because I have seen that while predicting for > 2 input frames, you dont invert it, which means you consider the predictions to be T0→-1 and T0→1. 

Am I correct?
