### ISSUE TITLE
Speed up the training process

### ISSUE THREAD

**Issue by WANG-KX** [nianticlabs/monodepth2#2]
Dear, 

Thanks a lot for your open source project!
As I reproduce the result, I found that the training time is longer than the reported time in the readme. I already moved the dataset to an SSD drive and used the default settings (I am using Titan XP, i7-7700, and pillow-simd). I am wondering do you have some extra operations, for example, pre-resize images?

For example: ```python train.py --model_name stereo_model2 --frame_ids 0 --use_stereo --split eigen_full``` costs about 14 hours.

**Comment by mdfirman** [comment]
Thanks for your report! 

I have run your command and it turns out that on an otherwise empty machine we actually get even better times than we reported in the paper (projected training time of around 6 hours 15 mins):

<img width="1154" alt="Screen Shot 2019-05-14 at 10 16 35 AM" src="https://user-images.githubusercontent.com/6114258/57686599-c4dfff00-7631-11e9-93db-5134bdff22c6.png">

 
Like you we are using Titan XPs, but we have stronger CPUs; we have two Xeons giving 40 cores in all.

To help you debug if your code is slow because of the GPU or because of the data loading/preprocessing, I have pushed a [new branch](https://github.com/nianticlabs/monodepth2/tree/training_profiling). If, like us, you are GPU-bound then you should see output something like this, with `0`s in the CPU column:

![image](https://user-images.githubusercontent.com/6114258/57686999-8ac32d00-7632-11e9-960d-c327c3c2d20a.png)

If on the other hand you are CPU bound then I agree that some form of caching or pre-resizing could help speed things up.

**Comment by WANG-KX** [comment]
Thanks for your quick reply!
I think it might be the CPU bottleneck. As I see in the htop that all processors are in 100%. I will try your new branch and gives out the result later.

**Comment by mdfirman** [comment]
Did you run these experiments in the end? I'm going to close this issue now as I feel this is a CPU limitation on your end. But feel free to reopen if you discover that there is a code problem that is slowing you down. 

Also, if you find any ways of speeding up training we are open to pull requests 😃.

Thanks
