### ISSUE TITLE
index of axisangle and translation in transformation_from_parameter function

### ISSUE THREAD

**Issue by Jinho-P** [nianticlabs/monodepth2#204]
Hi,

I have some questions. 
1. The transformations for T0->-1 and T0->1 are calculated using transformation_from_parameter function with 
axisangle and translation parameters.
But in code,
https://github.com/nianticlabs/monodepth2/blob/d1c5f03c38305cae4e68917e472d2f9d4eda0b98/trainer.py#L295
only index '0' for T0->-1 is used and index '1' is never used. 
I wonder if there is no problem with this.
I think it will cause error when someone modify this code for using poseNet for some training.

2. In your paper, source image is transformed to predicted target image (then target and predicted target images are used for loss). But In your code implementation, depth prediction from target image is transformed to predicted source image. Then source and predicted source image are used for loss. Did I get it right? 
(The reason that you take transformation of t->t+1 and t->t-1 (not t+1->t and t-1->t) is the difficulty of implementation and optimization)

**Comment by mdfirman** [comment]
Thanks for your interest in the repo!

1. See this issue https://github.com/nianticlabs/monodepth2/issues/120 which covers this query

2. No, you are not correct here. In the code, the source image is transformed to match the target image. The warping of the source image happens [here](https://github.com/nianticlabs/monodepth2/blob/master/trainer.py#L384), and the loss comparing this prediction to the (unwarped) target frame is [here](https://github.com/nianticlabs/monodepth2/blob/master/trainer.py#L428).

Does this answer your query?

**Comment by Jinho-P** [comment]
Hi, @mdfirman !!!
1. In conclusion, axisangle[:, 0], translation[:, 0] is used for transformation between -1 and 0 frame 
and axisangle[:, 1], translation[:, 1] is used for transformation between 0 and 1 frame where frame_ids = [0, -1, 1]
Source and destination are determined by 'invert=(f_i < 0)'. Is it right?

2. I had misunderstanding about that code.
This line [here](https://github.com/nianticlabs/monodepth2/blob/d1c5f03c38305cae4e68917e472d2f9d4eda0b98/trainer.py#L377), the input 'depth' is calculated from disp which output of depth decoder and means depth of target image. And 'cam_points' means reconstructed 3D point of target image in target frame. 
Then [here](https://github.com/nianticlabs/monodepth2/blob/d1c5f03c38305cae4e68917e472d2f9d4eda0b98/trainer.py#L379), by self.project_3d, reconstructed 3D point of target image in target frame is transformed to source image plane in source frame. And 'pix_coords' means pixel coordinate in source image of points which are seen from target image.

**Comment by mdfirman** [comment]
1. In actual fact – `axisangle[:, 1], translation[:, 1]` isn't used at all. In our published method, `num_pose_frames` is 2, so [this](https://github.com/nianticlabs/monodepth2/blob/master/trainer.py#L267) branch is used.
We loop over each frame [here](https://github.com/nianticlabs/monodepth2/blob/master/trainer.py#L276). The pose network is run once for transformation between 0 and 1, and once for transformation between 0 and -1. 
We convert `axisangle[:, 0] and translation[:, 0]` into a transformation matrix [here](https://github.com/nianticlabs/monodepth2/blob/master/trainer.py#L294). 

So that the pose network only has to learn about forward poses (and doesn't have to also learn about backwards poses), for (0, -1) transformation (i.e. when `f_i < 0`) we swap the ordering of the input features and then invert the resultant matricx

2. Yes, this sounds correct. And yes, the color_pred image will look a lot like the source image, especially at the start of training

**Comment by Jinho-P** [comment]
2. In my case, I try to custom datasets where training so hard. So after some iteration, color_pred images are more looks like source image even though not at the start of training. Then I misunderstand that color_pred images should similar to source image not target image. But It is wrong, right? 
If training is done well, color_pred images are should looks like target image not source image. (I was completely mistaken!!!)

**Comment by mdfirman** [comment]
yes that's right – color_pred should look like target image in the end

**Comment by Jinho-P** [comment]
Thanks to you, I was able to understand the content and implementation of the paper accurately.
I really appreciate this!!!!
