### ISSUE TITLE
Question about inputs["stereo_T"]

### ISSUE THREAD

**Issue by Darknesszlx** [nianticlabs/monodepth2#206]
camera left's prediction is thrown into 3D point cloud, and a transformation matrix T is used to transform 3d points from left camera to right. In stereo mode, inputs["stereo_T"] is the transformation matrix T. 
In dataset/monodataset.py line192-198, why the T is set like this?
https://github.com/nianticlabs/monodepth2/blob/d1c5f03c38305cae4e68917e472d2f9d4eda0b98/datasets/mono_dataset.py#L198
is it known in Kitti dataset?

**Comment by mrharicot** [comment]
Hi,
For the stereo images we assume that we know the transformation: it is a pure translation along the X axis:
https://github.com/nianticlabs/monodepth2/blob/d1c5f03c38305cae4e68917e472d2f9d4eda0b98/datasets/mono_dataset.py#L192-L196
I hope this helps!

**Comment by Darknesszlx** [comment]
Thanks for your reply！And another question is，Why translation along the X axis is 0.1 or -0.1？

**Comment by daniyar-niantic** [comment]
The two cameras are mounted to point in the same direction and offset horizontally from each other. They are also calibrated, so that the transformation between them is only along the X axis (horizontal transformation in the real world). The translation value is 0.1 or -0.1 depending if the transformation is from left camera to right camera, or vice versa. If you want to learn more about 3D multi-view geometry, I suggest checking out Section 5 of "[Computer Vision](http://www.computervisionmodels.com/)" book by S. Prince, or "Multiple View Geometry" by Hartley and Zisserman.
