### ISSUE TITLE
train mono model with my own data

### ISSUE THREAD

**Issue by CF2220160244** [nianticlabs/monodepth2#217]
When i train mono model with my own data, I change the self.K and self.full_res_shape in kitti_dataset.py, but the result is worse,  Can you gays give me some advices? Do i need change any other code? @mrharicot @mdfirman @daniyar-niantic

**Comment by WinstonDeng** [comment]
@CF2220160244 
1. Create your own dataset class inheriting from mono_dataset.py(change self.K, self.full_res_shape, get_image_path, ...)
2. Build your own dataset, and create a new split file(start and end images cannot be involved in split file due to frame_ids [0,-1,1])
3. Add your dataset class in __init__.py and trainer.py(datasets_dict)
4. Config corresponding global params, such as data_path, dataset, split, log_dir, eval_split, model_name
