### ISSUE TITLE
Training on more than 3 frames

### ISSUE THREAD

**Issue by YJonmo** [nianticlabs/monodepth2#226]
Thanks for this work

I get errors when I want to use more than a pair of frames (let say 0 -1 -2 1 2) to train the model using the separate_resnet as the pose encoder.

/Python/monodepth2-master> python train.py --data_path $DATA_Folder --split $Splits --log_dir $OUTPUT/ --png --no_eval --dataset Custom --height 256 --width 256 --frame_ids 0 -1 -2 -3 1 2 3 --use_stereo  --pose_model_input all

Traceback (most recent call last):
  File "train.py", line 18, in <module>
    trainer.train()
  File "/home/jonmoham/Python/monodepth2-master/trainer_orig.py", line 190, in train
    self.run_epoch()
  File "/home/jonmoham/Python/monodepth2-master/trainer_orig.py", line 206, in run_epoch
    outputs, losses = self.process_batch(inputs)
  File "/home/jonmoham/Python/monodepth2-master/trainer_orig.py", line 256, in process_batch
    outputs.update(self.predict_poses(inputs, features))
  File "/home/jonmoham/Python/monodepth2-master/trainer_orig.py", line 317, in predict_poses
    axisangle[:, i], translation[:, i])
IndexError: index 2 is out of bounds for dimension 1 with size 2

I can train the model when I am using the --pose_model_type posecnn but not when using the separate_resnet.

Also it would be nice to have a pieace of code to interpret the pose output when using other pose models such as posecnn which take more than two input images. If feed in 5 input images (0 -1 -2 1 2), then I get 4 outputs as the pose estimation, but I don't know how to interpret these number whereas the separate resnet only gets 2 input images and gives out one pose.

**Comment by mrharicot** [comment]
Hi,

First regarding the output of the pose network, it is simply the poses relative to the first index, which is why you get N - 1 outputs.

As for the `separate_resnet` issue, I looked into it and we originally wrote it only to handle pairs but didn't really seem to have tested it if we were to use it with more images.
https://github.com/nianticlabs/monodepth2/blob/101dd03f00e0d8e9bcd8a8d760f94bc2820f5549/trainer.py#L266

You can try to change this `if` statement and see whether it works.
