### ISSUE TITLE
clamp depth_pred only..why?

### ISSUE THREAD

**Issue by Jinho-P** [nianticlabs/monodepth2#249]
In your code, at 'compute_depth_losses' function , depth_pred is clamped range [1e-3 ~ 80].
This is for fair comparison to eigen's result. But I have some questions.

1. why depth_gt (lidar) is not clamped? I think it is more reasonable for accurately evaluating the model's performance.
depth_gt's range is [0 ~ maybe 100 over]. So, If we clamp depth_pred only, optimal accuracy and error metric can not be achieved.

2. If I train customized md2 with gt (for solving scale ambiguity) to predict metric (absolute ) depth, is clamping depth to [1e-3 ~ 80] still needed for fair comparison with other methods?

**Comment by mrharicot** [comment]
Hi,
Great questions!

1.  If I remember correctly the 80m clamp came from the original evaluation from Eigen. Garg chose 50m which is why you sometimes see two evaluations. I also think the total number of points beyond 80m is very very small and doesn't impact the results. But I agree it would be more fair to clamp the gt to 80m as well.
2. The standard evaluation (whether it is the best decision is up for debate) is to clamp at 80m, so for fairness and proper comparison with previous methods you should clamp to 80m. If you do not want to clamp you then need to recompute the results from the previous papers.

I hope this helps!
