### ISSUE TITLE
Question about predicted pose

### ISSUE THREAD

**Issue by hamzarawal** [nianticlabs/monodepth2#252]
Hi,
I noticed that you do not compare the predicted pose directly to the ground truth during pose evaluation, rather you apply some transformations before matching them. So my question is: is the predicted pose not the real pose? What transformations will I need to make it directly comparable with GT pose?

**Comment by mdfirman** [comment]
The standard method for pose evaluation is to evaluate on a sequence of five frames – this was established in Zhou et al.

However, our pose network only predicts pose for a pair of frames.

In order to evaluate on a sequence of five frames, we chain together four _relative_ pose predictions into a five-frame sequence of poses. These five poses need to all be relative to to camera at the start of the five-frame sequence. 
This 'chaining' of poses is what is happening [here](https://github.com/nianticlabs/monodepth2/blob/master/evaluate_pose.py#L114).

See also section A in the supplementary material.

Thanks
