### ISSUE TITLE
export_gt_depth seems to generate incorrect GT depths in the LIDAR coordinates

### ISSUE THREAD

**Issue by sconlyshootery** [nianticlabs/monodepth2#274]
https://github.com/nianticlabs/monodepth2/blob/ab2a1bf7d45ae53b1ae5a858f4451199f9c213b3/export_gt_depth.py#L49
https://github.com/nianticlabs/monodepth2/blob/ab2a1bf7d45ae53b1ae5a858f4451199f9c213b3/kitti_utils.py#L74
It seems to generate incorrect GT depths in the LIDAR coordinates, I think it is appropriate to setting generate_depth_map(calib_dir, velo_filename, 2, False) in export_gt_depth.

**Comment by mrharicot** [comment]
Hi,

This mistake dates back from Eigen's seminal paper.
We kept it when writing the evaluation of monodepth1 for consistency, which looking back probably wasn't the smartest move.
However when testing with the flag on or off we could not see much of a difference and the ranking of methods wast left unchanged, mostly due to the fact that this evaluation is very flawed in the first place.
Namely the lidar points should be "untwisted" when the car is moving, and samples are incorrect around boundaries and thin objects.

I strongly recommend people to use the new improved depth benchmark `eigen_benchmark` for evaluation as it does not suffer from these issues.

**Comment by sconlyshootery** [comment]
Thank you for your advice, you have been very helpful!

**Comment by sconlyshootery** [comment]
Sorry to bother you again, I want to generate eigen_benchmark from rawdata, but fail to find proj_depth/groundtruth/ folder, where could I download it.
Is it right to download it from KITTI depth prediction evaluation?
Which one should I download?
![Screenshot from 2020-11-17 15-57-52](https://user-images.githubusercontent.com/15374408/99361844-af662800-28ed-11eb-9696-d1ceaae71fc2.png)

Thank you in advance!

**Comment by alwynmathew** [comment]
http://www.cvlibs.net/download.php?file=data_depth_annotated.zip

**Comment by miniMaddy** [comment]
Hello, @sconlyshootery , I tried running this but I am getting this value error due to the different sizes of the ground depth, did you also face the same issue?

Error:
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (652,) + inhomogeneous part.

Thanks for the help.
