### ISSUE TITLE
How to deal with the texture-copy artifacts?

### ISSUE THREAD

**Issue by LukeCho-8810** [nianticlabs/monodepth2#284]
Hi, 

I noticed that there were several regions with texture-copy artifacts on my custom data?  Could you give me some advices on how to deal with that?

Thanks

**Comment by mdfirman** [comment]
Hi, thanks for your interest in this project!

Is your own data a stereo or a mono dataset? Typically texture-copy might come in:

-  if stereo images are badly calibrated, or
-  if the pose network is struggling to predict good poses (e.g. if the motion is too big or unpredictable)
- or if the intrinsics are wrong

It could also be some other problem.

**Comment by LukeCho-8810** [comment]
> Hi, thanks for your interest in this project!
> 
> Is your own data a stereo or a mono dataset? Typically texture-copy might come in:
> 
> * if stereo images are badly calibrated, or
> * if the pose network is struggling to predict good poses (e.g. if the motion is too big or unpredictable)
> * or if the intrinsics are wrong
> 
> It could also be some other problem.

Hi, thanks for your reply.

My own data is stereo vedio dataset. I trained on it using the mono+stereo training mode.

And I checked my data, the calibration results was not that bad. And our framerate is about 25fps, so i assumed that pose was not that unpredictable.

I have 2 questions:

1)  I want to ask that whether Monodepth2 is sensitive to intrinsics. In my expeiment, I mixed my custom data with other datasets with different intrinsics. But I found that in monodepth1 there were experiments conducted on mixed data of cs(cityscape)  and kitti. While in monodepth2, the model only trained on kitti. And in both methods, crop and resize was not used to augment the data.

2) Could you please tell me why there are texture-copy artifacts in the result? I can't figure out the reason behind this problem. And I find that in monodepth1, predicting the disparity maps for both views would help this. Why would it work and will it be helpful to my problem?

Thanks!

**Comment by mdfirman** [comment]
Hi again,

1. Yes Monodepth2 is sensitive to intrinsics. So you should definietely make sure that each loaded training image has its own correct intrinsics loaded.
2. I don't know the answer to this question. As I say before, this is typically because of some problem in the pose estimation, intrinsics or calibration. You could consider trying your data on a different open-source repo (e.g. https://github.com/anuragranj/cc) to help to debug.  

As you have stereo data, you could try running a simple stereo matching algorithm (e.g. OpenCV's SGM) to see how good the depth maps are. This could help to see how well calibrated your stereo images are. If these depths are good then you could consider training directly from these depth maps.

Thanks
