### ISSUE TITLE
How much time will be saved by using JPG instead of PNG?

### ISSUE THREAD

**Issue by whyygug** [nianticlabs/monodepth2#293]
Just wondering if it will save a few hours, or a dozen?
Is it a common feature that Pytorch (or PIL) can read JPG faster than PNG?
Thanks！

**Comment by mrharicot** [comment]
Hi,

I don't have an actual estimate of how much time you would save and it actually depends on your machine.

PNGs encoding natural images just take a lot more disk space, which means that reading them will take more time.
For KITTI, PNGs are ~850kB and the JPGs are ~150kB which is a 5.5X difference, when training on an old SSD (like we were for monodepth1 and 2) with limited read speed the difference was enough that we were not IO bound anymore, but your experience might be different now that NVMe drives reach multiple GB/s of read speeds. You however exchanged read speeds for decode time on the CPU, but if you have a big enough CPU this won't be a problem.

The rule of thumb is to be GPU limited when training (use your GPUs as much as possible) so it is best to adapt the rest of your code/data to ensure that is the case: you want to feed as much data to your GPU as possible so that you train in the least amount of time.

I hope this helps!

**Comment by whyygug** [comment]
Thank you for your reply. It is always a pleasure to communicate with you and I can learn a lot.
Thanks again!
