### ISSUE TITLE
Stereo trained with baseline 0.1

### ISSUE THREAD

**Issue by alwynmathew** [nianticlabs/monodepth2#30]
The models which were trained with stereo supervision were trained with a nominal baseline of 0.1 units. 

https://github.com/nianticlabs/monodepth2/blob/5cc5c85e70d4788ce33b3461e63f8a5b810f2776/datasets/mono_dataset.py#L196

The KITTI rig has a baseline of 54cm. Therefore,  to convert the stereo predictions to real-world scale you multiply the depths by 5.4.

https://github.com/nianticlabs/monodepth2/blob/5cc5c85e70d4788ce33b3461e63f8a5b810f2776/evaluate_depth.py#L24

Is there any significance in training with a nominal baseline of 0.1?

**Comment by daniyar-niantic** [comment]
Hi @alwynmathew ,

In theory you should be able to get the same results with the baseline of 0.54. However, you might also need to modify you network initialization as the random predictions of the network at the very beginning of the training (think about batch 0 predictions) will be in a different range (they might not span the depths between min_depth and max_depth) . This can be fixed by re-scaling the random weights. This modification would potentially also apply to the pose network.

Best,

Daniyar

**Comment by alwynmathew** [comment]
@daniyar-niantic thank you for the response. Though my question was different. @mdfirman  My question:

Why did you use 0.1 baseline while training instead of the original baseline 0.54?

**Comment by daniyar-niantic** [comment]
So, the main reason of using 0.1 baseline is the stability of training. The random initialization of the network starts converging with KITTI dataset. If you change the baseline, the random initiallization may be in a different range and you may not be able to train.

**Comment by alwynmathew** [comment]
@daniyar-niantic thank you for the insight. I tried changing the baseline to 0.54 and training the network. As expected it didn't work. 

> If you change the baseline, the random initialization may be in a different range and you may not be able to train.

If I want to change the baseline to 0.54, how do I find the "random initialization range" that should enable proper network training?

**Comment by daniyar-niantic** [comment]
You can read a bit on different initialization schemes, for example [this blogpost](https://towardsdatascience.com/weight-initialization-techniques-in-neural-networks-26c649eb3b78) covers some of them. 

You need to match the output range of depths produced by network with baseline 0.1 and baseline 0.54.
So, investigate the range of depth predictions when a random initialization with baseline 0.1 is used. Then, for baseline 0.54, investigate how you should scale every layer, so that a random network produces the range of depths as similar as possible to the "0.1 baseline network".

Alternatively, you can always use "trial and error" method. So, you multiply the random network weights with different scalings and see which one converges.

The exact implementation of these procedures is outside the scope of this project.
