### ISSUE TITLE
Distance from Depth

### ISSUE THREAD

**Issue by ShoaibSajid** [nianticlabs/monodepth2#309]
Hi. Thank you for sharing this beautiful code.
I am a beginner in this field and I need some help.

Currently I am using a single image and finding out its disparity map.
When I try to convert the disparity into distance, I have this formula.
depth = (baseline * focal length) / disparity)
I do have the focal length of my camera and the disparity from your algorithm, but since I am using just a single camera so what woud be the baseline?

If you have any snippet of code calculating distance, could you share that as well

**Comment by mrharicot** [comment]
Hi,

Monodepth2 predicts a scaled depth, which means you need a single factor to convert the depth into metric depth.
However since it was trained only on KITTI, if you test it on a different image it is unclear what the model will predict.
Please see this thread for more info.
https://github.com/nianticlabs/monodepth2/issues/47

I hope this helps!
