### ISSUE TITLE
why do we need the track_length?

### ISSUE THREAD

**Issue by sunnyHelen** [nianticlabs/monodepth2#32]
https://github.com/nianticlabs/monodepth2/blob/1cc8b81b6ca46fc6878de92ff126c7d2d94f5f89/evaluate_pose.py#L118
why do we need the track_length when evaluating pose result?
Thank you for your help~

**Comment by mdfirman** [comment]
Thanks for this question.

When evaluating pose, we want to ensure a fair comparison with previous works.

[Zhou et al](https://people.eecs.berkeley.edu/~tinghuiz/projects/SfMLearner/cvpr17_sfm_final.pdf) evaluated pose over sequences of five frames, and they trained their pose network to predict for five frames at a time for this evaluation. 

Our code only predicts pose for *pairs* of frames. To be able to evaluate on sequences of length 5, we chain our pairwise predictions together to make five-frame predictions. The `track_length` constant is set to control this evaluation sequence length.

We have more details in the pose evaluation section of our supplementary material.

**Comment by sunnyHelen** [comment]
Ok, thank you very much~

**Comment by sunnyHelen** [comment]
Sorry to bother you again.
If I want to train with 5-frame sequence, I need to change [0, -1, 1] to [0, -2, -1, 1, 2]. Is it right? Does the order of these frames matter?
![image](https://user-images.githubusercontent.com/28101548/60631450-cadcaa00-9e42-11e9-8f48-60363a6c188c.png)

**Comment by sunnyHelen** [comment]
@mdfirman

**Comment by mdfirman** [comment]
> I need to change [0, -1, 1] to [0, -2, -1, 1, 2]. Is it right?

Sort of. In theory most of the code _should_ work with frame ids other than [0, 1, -1]. However, we have never tested this setup, so you might have to do some debugging. The one bit I'm pretty sure will need to change is the data loading. The current eigen splits (defined in `splits/` folder) exclude the frame at the start and end of each sequence, so that t-1 and t+1 can always be loaded. When you load t-2 and t+2, you will probably throw an error as the file won't exist. You will have to find a way to deal with this problem: maybe recreate the splits files, or change the dataloader so if it can't find a file it returns zeros.

> Does the order of these frames matter?

No, as long as 0 is first.

**Comment by sunnyHelen** [comment]
Got it. Thanks a lot!
