### ISSUE TITLE
How to get actual distance from the mono_1024x320 model ?

### ISSUE THREAD

**Issue by rafiqul713** [nianticlabs/monodepth2#329]
How can I get the actual distance in the meter unit from the mono_1024x320 model? For stereo, we need to use stereo supervision (that is 5.4 for the KITTI dataset) to get the actual depth. For the mono_1024x320 model, is there any scale factor that exists? If so, what is that scale factor? 

Thanks in advance.

**Comment by mrharicot** [comment]
Hi,

Monodepth2 predicts a scaled depth, which means you need a single factor to convert the depth into metric depth.
However since it was trained only on KITTI, if you test it on a different image it is unclear what the model will predict.
Please see this thread for more info.
#47

I hope this helps!

**Comment by mrharicot** [comment]
Hi,

To get the scale for mono models you need to run the KITTI evaluation code which will output the average scale at the end.

I hope this helps!
