### ISSUE TITLE
Problems on png images of custom dataset

### ISSUE THREAD

**Issue by hubery4** [nianticlabs/monodepth2#356]
Hi,

Thank you for reviewing my question.
When I train the net on my own dataset which contains 'png' images with 24-bit, there is always an error that 'no such file or directory'.
![1](https://user-images.githubusercontent.com/47403404/120922249-ed773d80-c6bf-11eb-9c88-b9ba7ddaa7da.png)
I do not know what happened to this, since each time it reports the same error but with a different png image route. Does the question relate to png and jpg format? Should I convert png to jpg?
But when I see your github file, it says that 'png' also works, just has slower running time?

Thank you if you could give me some suggestions.

**Comment by mdfirman** [comment]
Thanks for your interest in this project.

To me this looks like a problem with the new code you have added, rather than the code we have provided.

Can you make sure that this file exists on your hard drive:

![image](https://user-images.githubusercontent.com/6114258/120938820-be3aed80-c70c-11eb-8ae9-21932ae9070a.png)

If it doesn't – then that is your problem. You either need to move the data to be in the place the code expects it to be, or modify the code to point to the correct place that the data is in.

Thanks

**Comment by hubery4** [comment]
@mdfirman 
Thank you for your response.
I have correct it due to that data_path I set in the new code was wrong

**Comment by mdfirman** [comment]
Great – glad you got it fixed
