### ISSUE TITLE
TypeError: 'dict' object is not callable

### ISSUE THREAD

**Issue by biggiantpigeon** [nianticlabs/monodepth2#367]
Hi, 
I run into an error while training with my own data and I cannot find it out:
![image](https://user-images.githubusercontent.com/80443901/122387581-961b7c00-cfa1-11eb-9577-ea9f8dff3b01.png)
Anyone have any clue about this? 
my pytorch version is 1.0.0.
Thanks.

**Comment by mdfirman** [comment]
Thanks for your interest

You appear to have modified the trainer code, and I'm not quite sure what you are trying to do here
```
self.model_optimizer.step(losses)
```

The `step` function in Adam takes a single parameter `closure`, which is expected to be a callable.
https://pytorch.org/docs/stable/_modules/torch/optim/adam.html#Adam

In your code it looks like you are providing a dictionary `losses` rather than a callable.

![image](https://user-images.githubusercontent.com/6114258/122403357-39569c00-cf76-11eb-8811-48125c22f361.png)

**Comment by biggiantpigeon** [comment]
Sorry it's my fault, thanks for your patience.
