### ISSUE TITLE
How to prevent holes during training?

### ISSUE THREAD

**Issue by dsGonz** [nianticlabs/monodepth2#39]
Hello,

First off, thank you for all your hard work on this. I really enjoyed reading your paper and learning about the method.

I'm currently training the model on my own dataset. It's an indoor office-type setting with a lot more low texture regions than KITTI (blank walls and floors). I read in the paper that these regions can give rise to "holes" in the lower resolution depth maps and I can see signs of this  after the first epoch of training. As training goes on, the holes get worse to the point where all resolutions are hole patterns or completely blank.

Any tips on how to make the model more robust to these artifacts? I was thinking of adjusting the number of scales or maybe changing alpha in the photometric error. 

Also, the video sequences were taken at 30 fps. I noticed that adjacent frames did not look very different than the target image. Could this also be contributing to the holes?

I also want to avoid going through my data and removing clips with a lot of low texture. 

Thank you

**Comment by mdfirman** [comment]
Hi @dsGonz ,

Thanks for your interest in this. Where you have low texture regions, this breaks a fundamental assumption of self-supervised training (i.e. that depths can be recovered by matching pixels between camera views). Finding a method to fix this problem is a research problem in itself, and if you have interest and opportunity the community would be interested in efforts you make in this direction. Certainly some of the things you have suggested might work, or you could somehow detect low-texture regions and downweight their influence in the loss.

I agree that going for frame ids `-1 0 +1` for a 30fpd sequence might be too small a baseline in general. You could consider using frame ids more widely spaced, e.g. `-2 0 +2` or perhaps even more.
