### ISSUE TITLE
Regarding the License

### ISSUE THREAD

**Issue by mive93** [nianticlabs/monodepth2#412]
Dear authors,

first of all, thanks for the nice work.
Me and @perseusdg have been working on a porting of your model to [tkDNN](https://github.com/ceccocats/tkDNN), a framework that we have developed to boost NN performances on NVIDIA boards, and specifically on embedded ones. We completed the porting and we managed to make it work, and now we have some doubts regarding how to proceed with respect to your license.
We would like to publicly upload  weights (that are just yours in a different format), but we wanted to make sure that this was fine with you. 
Our project is released as GPLv2 (so, non-commercial), therefore there should be no problem, but still I would like to hear from your side.

Thank you in advance.
Micaela

**Comment by daniyar-niantic** [comment]
Hi.

Cool project!

The network weights that are shared in this repo are for mainly reproducibility and research purposes. They were generated using KITTI data that has its own license, etc.
I would suggest for you to not share the weights (not just due to our license, but also KITTI license), but rather share format conversion script and point to this repository for network weights.

Thanks!

**Comment by mive93** [comment]
Thank you @daniyar-niantic,

that's exactly what I did. 

Best,
Micaela
