### ISSUE TITLE
Channel size does not fit in pose decoder model

### ISSUE THREAD

**Issue by aartykov** [nianticlabs/monodepth2#418]
Hello. I am trying to train the network in KITTI dataset. The problem is that when the features are passed from pose encoder to pose decoder, the channel sizes do not fit into "self.conv["squeeze"]" layer. Because this layers input channel number was specified as 512 in the constructor, however, in the forward function, we pass all the last features with various channel sizes through this layer. Hence, there is inconsistency in the channel sizes. I hope, I could explain the problem clearly. Thanks in regard.

**Comment by dantkz** [comment]
Hi. As far as I know the current codebase works in corresponding virtual environment. So if you have modified something and it has caused an error, then you are asking for help with debugging without providing any details.

**Comment by giannisbdk** [comment]
Hello, I would like to follow this question up, since it did not answered.

Indeed, the output of the resnet encoder is a list containing the intermediate outputs of all the resnet's stages:

```python
def forward(self, input_image):
        self.features = []
        x = (input_image - 0.45) / 0.225
        x = self.encoder.conv1(x)
        x = self.encoder.bn1(x)
        self.features.append(self.encoder.relu(x))
        self.features.append(self.encoder.layer1(self.encoder.maxpool(self.features[-1])))
        self.features.append(self.encoder.layer2(self.features[-1]))
        self.features.append(self.encoder.layer3(self.features[-1]))
        self.features.append(self.encoder.layer4(self.features[-1]))
        # My comment:
        #The result here is:
        # list = [tensor[N, 64, 1/2*s, 1/2*s], tensor[N, 64, 1/4*s, 1/4*s], \
        #           tensor[N, 128, 1/8*s, 1/8*s], tensor[N, 256, 1/16*s, 1/16*s] \
        #           tensor[N, 512, 1/32*s, 1/32*s]]
        # where s: original image size h, w, resp.
```

This list of features is, then, fed into the (pose) decoder network, where the forward method is doing the following:

```python
def forward(self, input_features):
        last_features = [f[-1] for f in input_features]

        cat_features = [self.relu(self.convs["squeeze"](f)) for f in last_features]
        cat_features = torch.cat(cat_features, 1)

        out = cat_features
        for i in range(3):
            out = self.convs[("pose", i)](out)
            if i != 2:
                out = self.relu(out)

        out = out.mean(3).mean(2)

        out = 0.01 * out.view(-1, self.num_frames_to_predict_for, 1, 6)

        axisangle = out[..., :3]
        translation = out[..., 3:]

        return axisangle, translation
```

However, I cannot see how the `self.relu(self.convs["squeeze"](f))` can work, since this was declared in the constructor like:

```python
self.convs[("squeeze")] = nn.Conv2d(self.num_ch_enc[-1], 256, 1)
# My comment:
# self.num_ch_enc = [64, 64, 128, 256, 512], so self.num_ch_enc[-1] = 512
```

Please, note that that I did not run the code.
It seems that in the class constructor a convolutional operation is declared that waits an input volume with #  input channels as of the resnet's last stage (which is indeed as of the paper, see Table 5). However, there is a mismatch between the pose network introduced in the paper, and the actual implementation regarding the forward method.

**Comment by daniyar-niantic** [comment]
Hi @johnbdk ,
Can you please specify what options you are using? The result of ResnetEncoder is not directly passed to PoseDecoder, PoseDecoder typically receives a list of `tensor[N, 512, 1/32*s, 1/32*s]` features.
See:
https://github.com/nianticlabs/monodepth2/blob/master/trainer.py#L262

**Comment by giannisbdk** [comment]
@daniyar-niantic Apologies for opening a new issue after replying to this one (I was planning to delete it). I thought it was more proper to create a new one rather than having a discussion on a closed one. I can delete this answer from this issue or delete the entire new issue to avoid repetition.
