### ISSUE TITLE
Paramter Adjustment on custom training data

### ISSUE THREAD

**Issue by zzzzzyh111** [nianticlabs/monodepth2#432]
Hi,
I have some questions about changing parameters according to my custom training data.

Q1: I noticed that the intrinsic matrix for KITTI is a 3x4 matrix while my intrinsic matrix is a 3x3 matrix, should I reshape mine to KITTI's shape or do nothing?

Q2: I also got rotation and translation information from my dataset, should I replace the previous parameters with my rotation and translation parameters?

Looking forward to your early reply!

**Comment by daniyar-niantic** [comment]
Q1. The intrinsics matrix is 4x4. You should reshape yours to 4x4, so that the top 3x3 is your intrinsics matrix, the bottom right value is 1 and other values are 0. See https://github.com/nianticlabs/monodepth2/blob/master/datasets/kitti_dataset.py#L29

Q2. Are you using stereo dataset? If so, then you should use your rotation and translation information to set your extrinsics matrix. If your dataset is mono and you have camera pose information, then you could use it to train your model. See https://github.com/nianticlabs/monodepth2/issues/237
