### ISSUE TITLE
Can fog be synthesized on remote sensing images?

### ISSUE THREAD

**Issue by llz20180725** [nianticlabs/monodepth2#439]
Can fog be synthesized on remote sensing images?
I want to fog my remote sensing image

**Comment by daniyar-niantic** [comment]
Not sure how your question is relevant to this repo.

If remote sensing image is RGB image, then you can augment it using augmentation libraries to have fog effect. Since fog amount is dependent on depth of surfaces, I think this will have limited success, unless the augmentation libraries can do something special.

If remote sensing image is not RGB, then I don't think this is the repo for your question.
