### ISSUE TITLE
Questions about inverse warping

### ISSUE THREAD

**Issue by xiat0616** [nianticlabs/monodepth2#442]
Hi, 
Nice work. I do have some confusions about inverse warping.

I see in the function, you first convert 2D images to its world coordinates. For each pixel, there would be (x,y,z) representing its location. My question is why you use the depth of target image to represent z for world coordinates of source image, instead of use the depth of source image to represent it? Thank you.

**Comment by daniyar-niantic** [comment]
The 2D coordinate grid of the target frame is lifted into 3D using depth of target frame. Then it is projected to source image. The projected locations allow us to fetch colors from source frame and compare then against colors of target frame. This way, there are no holes in "target frame reconstructed using pixels of source frame" and we do not need to model occlusions.

See: https://github.com/nianticlabs/monodepth2/issues/65

**Comment by dumyCq** [comment]
Hi, I really appreciate the excellent work here. However, I am confused about the similar questions.
in trainer.py line 249, the depth prediction is from inputs["color_aug", 0, 0], which is from frame_id 0
But, they use the depth from frame_id 0 to lifted up the inputs[("color", 1, source_scale)] and inputs[("color", -1, source_scale)]
to the 3D world in trainer.py line 385. This makes me confused.

**Comment by dumyCq** [comment]
ChatGPT gave the answer is to simplify the learning process, I also find out if I change make it correct, it requires a very precise estimation of depth and camera motion and this is not possible at the start, leading my training ends up with failure.

**The Core of Unsupervised Depth Estimation**
Unsupervised depth estimation models like Monodepth2 leverage the concept of photometric consistency as a training signal. The idea is to use the consistency between a target image and a synthetic image (created by warping a source image to the target perspective) to learn depth. This process does not require ground truth depth maps but instead relies on the assumption that the world is static and the main changes between frames are due to camera motion.

**Why Use the Target Frame's Depth**
Direct Learning Signal for Depth Estimation: The goal is to estimate depth from a single image accurately. By using the target frame's depth to warp the source into the target perspective, the model directly optimizes the depth predictions for the kind of images it will encounter during inference. This direct optimization loop enhances the model's ability to predict depth maps that, when used to warp a source image, will closely resemble the target image.

**Temporal Consistency and Camera Motion:** 
In dynamic scenes captured in a sequence of images, the exact spatial arrangement of objects from the camera's perspective changes over time. By estimating the depth of the target frame and using this to warp a source frame, the model learns to account for these changes in a way that reflects how objects move and how their depth relative to the camera changes over time. This is a way to implicitly encode the camera motion and scene dynamics into the depth estimation process.

**Simplifying the Learning Problem:** 
Attempting to backproject the source image using its own depth and then reproject it into the target frame's perspective would require accurate depth estimation for both frames and a precise understanding of the relative camera motion between the two frames. While this is theoretically possible, it complicates the learning process and requires additional constraints or information (like accurate camera pose information between frames). Monodepth2 simplifies this by focusing on learning depth from the target frame's perspective, using known or estimated camera poses to guide the warping process without needing to accurately estimate the depth of every frame in a sequence beforehand.

**Implicit Camera Pose Estimation:** 
By optimizing the reprojection error (the difference between the target image and the warped source image), the model implicitly learns about the camera movement and scene geometry that best explain the observed changes between the source and target frames. This means that even though the depth of the target frame is used for warping, the process encourages the model to learn depth estimations that are consistent with both the static parts of the scene and the dynamics of camera motion.

Conclusion
In essence, the choice to use the target frame's depth for warping the source frame, rather than using each frame's own depth, is driven by the goal of simplifying the learning process, focusing the learning signal on the direct task at hand (depth estimation from single images), and leveraging the sequence of images to encode both static and dynamic aspects of the scene through an unsupervised learning framework. This strategy allows for effective depth estimation without requiring explicit depth labels or detailed camera pose information, making it highly versatile and applicable to a wide range of environments and camera setups.

**Comment by dumyCq** [comment]
> Hi, Nice work. I do have some confusions about inverse warping.
> 
> I see in the function, you first convert 2D images to its world coordinates. For each pixel, there would be (x,y,z) representing its location. My question is why you use the depth of target image to represent z for world coordinates of source image, instead of use the depth of source image to represent it? Thank you.

you can treat F.grid after all doing the backward wrapping
